services:
  db:
    image: postgres:latest
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - db_password
    environment:
      POSTGRES_USER: quantumhive
      POSTGRES_DB: quantumhive
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password  # Point to secret
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quantum_hive_network  # Connect to the custom network to ensure no outside access
  redis:
    image: redis:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - quantum_hive_network  # Connect to the custom network to ensure no outside access

  # Uvicorn server
  uvicorn:
    image: quantumhive/uvicorn-server:latest
    volumes:
      - minimizer_data:/data  # Persistent storage for vector files
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - db_password
      - jwt_secret
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password  # Point to secret
    depends_on:
      - db  # Ensure the database is started before the Uvicorn service
      - redis  # Ensure Redis is started before the Uvicorn service
    ports:
      - "8000:8000"  # Expose the Uvicorn server on port 8000
    networks:
      - quantum_hive_network # Connect to the custom network to ensure no outside access

networks:
  quantum_hive_network:  # Define a custom network
    driver: bridge

secrets:
  db_password:
    external: true  # Tells Docker to use an existing secret
  jwt_secret:
    external: true  # Tells Docker to use an existing secret

volumes:
  postgres_data:  # Define the persistent volume for postgres
    driver: local  # Use the local driver. This means that the volume is stored on the host machine inside the docker volume directory, and will persist even if the container is removed
  minimizer_data:   # Declare the named volume for saving vector files
    driver: local   # Use the default Docker volume driver